ENH: Add bindings to `ase` [Topo1D]
d-SEAMS/PydSEAMSlib pull request #11
Opened 2024-07-22 22:35 UTC by RuhiRG

Added approval tests, which will be used to ensure the right behavior of the wrapper.

2024-07-22 23:27 UTC, RuhiRG commented
Initial mapping of LAMMPS to ASE gives:

```python
In [2]: %%timeit
   ...: _ase.map_1({1: 'H', 2: 'O'}, atms)
   ...: 
   ...: 

1.46 ms ± 38.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [3]: 

In [3]: %%prun -s cumulative -q -l 10 -T prun0
   ...: _ase.map_1({1: 'H', 2: 'O'}, atms)
   ...: 
   ...: 
 
*** Profile printout saved to text file 'prun0'.

In [4]: print(open('prun0', 'r').read())
   ...: 
         22082 function calls (20577 primitive calls) in 0.014 seconds

   Ordered by: cumulative time
   List reduced from 45 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1502    0.001    0.000    0.009    0.000 atoms.py:1096(__iter__)
      2/1    0.000    0.000    0.009    0.009 {built-in method builtins.exec}
      2/1    0.000    0.000    0.009    0.009 <string>:1(<module>)
      2/1    0.001    0.001    0.009    0.009 _ase.py:10(map_1)
     1500    0.003    0.000    0.008    0.000 atoms.py:1100(__getitem__)
     1500    0.001    0.000    0.003    0.000 {built-in method builtins.isinstance}
     1500    0.000    0.000    0.003    0.000 <frozen abc>:117(__instancecheck__)
     1500    0.001    0.000    0.002    0.000 atom.py:20(getter)
     1500    0.001    0.000    0.002    0.000 {built-in method _abc._abc_instancecheck}
3004/1502    0.001    0.000    0.002    0.000 {built-in method builtins.len}
```

Where the implementation is:

```python
def map_1(dict_map: dict(), atms_a: ase.Atoms):
    for key, value in dict_map.items():
        for pt in atms_a:
            if pt.number == key:
                pt.symbol = value
    return atms_a
```

2024-07-22 23:37 UTC, RuhiRG commented
Reordering to:

```python
def map_2(dict_map: dict(), atms_a: ase.Atoms):
    for pt in atms_a:
        if pt.number in dict_map.keys():
            pt.symbol = dict_map[pt.number]
    return atms_a
```

Gives:

```python
In [1]: %%timeit
   ...: _ase.map_2({1: 'H', 2: 'O'}, atms)
   ...: 
   ...: 
965 μs ± 15.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
In [3]: %%prun -s cumulative -q -l 10 -T prun0
   ...: _ase.map_2({1: 'H', 2: 'O'}, atms)
   ...: 
   ...: 
 
*** Profile printout saved to text file 'prun0'.

In [4]: print(open('prun0', 'r').read())
         13827 function calls (13073 primitive calls) in 0.008 seconds

   Ordered by: cumulative time
   List reduced from 45 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      751    0.000    0.000    0.004    0.000 atoms.py:1096(__iter__)
      750    0.001    0.000    0.004    0.000 atoms.py:1100(__getitem__)
      2/1    0.000    0.000    0.003    0.003 {built-in method builtins.exec}
      2/1    0.000    0.000    0.003    0.003 <string>:1(<module>)
      2/1    0.001    0.001    0.003    0.003 _ase.py:18(map_2)
      750    0.000    0.000    0.002    0.000 {built-in method builtins.isinstance}
     1250    0.000    0.000    0.002    0.000 atom.py:20(getter)
      750    0.000    0.000    0.001    0.000 <frozen abc>:117(__instancecheck__)
     1250    0.001    0.000    0.001    0.000 atom.py:157(get)
      750    0.000    0.000    0.001    0.000 {built-in method _abc._abc_instancecheck}
```

2024-08-26 01:05 UTC, HaoZeke requested changes
Almost there, shaping up nicely.

2024-08-26 01:05 UTC, HaoZeke commented on src/adapters/_ase.py
> +    return atms_a
Good to see the benchmarking for these on the issue, however for the final PR please ensure only one variant is present.

2024-08-26 01:05 UTC, HaoZeke commented on .github/workflows/build_test.yml
Perhaps worth building on `windows` and `macos` as well

2024-08-26 01:05 UTC, HaoZeke commented on ase_topo1d.py
This should be part of the documentation OTOH, since it seems to be an example.

2024-08-26 01:09 UTC, HaoZeke commented on .github/workflows/build_test.yml
> +          pip install pytest approvaltests pytest-approvaltests "ase>=3.23.0"
Should this perhaps be simply `pip install .[testing,adapters]` ?

2024-08-26 01:37 UTC, HaoZeke commented on ase_topo1d.py
Maybe this should be in a follow up PR.

2024-08-26 02:20 UTC, HaoZeke commented
Windows CI seems to have [some linking errors](https://github.com/d-SEAMS/PydSEAMSlib/actions/runs/10552342289/job/29231016123?pr=11) even after attempts to use static linkage. Can be left for a later PR.

2024-08-26 04:28 UTC, HaoZeke requested changes
Almost done, the tests can be cleaned a bit before this goes in. Some of the other `.py` files are clearly documentary / examples but those can be migrated in another PR.

2024-08-26 04:28 UTC, HaoZeke commented on tests/test_ase_topo1d.py
> +    verify(pprint.pformat(nList))
This should be `nl` in the verification, and after the approved set has been obtained (once) with `nList` it can be cleaned up more.

2024-08-26 04:28 UTC, HaoZeke commented on tests/test_ase_topo1d.py
> +    verify(pprint.pformat(hl))
See discussion above.

2024-08-26 04:33 UTC, RuhiRG commented on tests/test_ase_topo1d.py
> +    verify(pprint.pformat(nList))
The assertion `nList[idx]==nl[idx]` needs both to be present..

2024-08-26 04:34 UTC, HaoZeke commented on tests/test_ase_topo1d.py
> +    verify(pprint.pformat(nList))
Fair, but the `assert` is redundant with the approval test in this situation, so I think it can be cleaned up still.

2024-08-26 04:39 UTC, HaoZeke approved these changes
LGTM, thanks for working on this @RuhiRG!

2024-08-26 04:40 UTC, merged